### ISSUE TITLE
Nice to have: templates for view/change views

### ISSUE THREAD

**Issue by bob-r** [ctxis/django-admin-view-permission#5]
- view_form.html: object tool "Change"
- change_form.html: breadcrumb " > Change"

**Comment by lefterisnik** [comment]
Hi @bob-r ,

Thanks for the issue.

What do you mean with this: `object tool "Change"` and with this `breadcrumb "> Change"`?

Right now, the package uses only the change_form.html as you already noticed because it has all the appropriate functionality. The package makes use of the `get_readonly_fields` to display the fields as readonly (view permission). Why do you need a separate view_form.html? Could you provide me a use case where you need a separate template?
